export const COVER_PHOTO_MAX_FILE_SIZE_MB = 10;
export const COVER_PHOTO_MAX_FILE_SIZE_BYTES =
  COVER_PHOTO_MAX_FILE_SIZE_MB * 1024 * 1024;

export const COVER_PHOTO_RECOMMENDED_WIDTH = 1920;
export const COVER_PHOTO_RECOMMENDED_HEIGHT = 1080;
export const COVER_PHOTO_MIN_WIDTH = 1280;
export const COVER_PHOTO_MIN_HEIGHT = 720;
